before_install: gem install bundler -v '1.15.0'
rvm:
  - 2.2.0
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
